[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day01b"
path = "src/day01b.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[[bin]]
name = "day02b"
path = "src/day02b.rs"

